[project]
name = "personal-assistant"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Ankit Tiwari", email = "ankittiwaari@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "asyncpg>=0.31.0",
    "dotenv>=0.9.9",
    "gradio>=6.26.0",
    "openai-agents[sqlalchemy]>=0.21.1",
    "pygame>=2.6.1",
    "sarvamai>=0.1.31",
    "tavily>=1.1.0",
]

[project.scripts]
personal-assistant = "personal_assistant:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "ruff>=0.16.5",
]
